### ISSUE TITLE
Where is release.zip? All there is is a source code.

### ISSUE THREAD

**Issue by R3dXIII** [zbeboy/Tidy2#2]
Install instructions say download release.zip but where is release.zip? All there is is a source code.

**Comment by zbeboy** [comment]
Oh hi, Is here [releases](https://github.com/zbeboy/Tidy2/releases/tag/1.0) , not release.zip.

**Comment by zbeboy** [comment]
@R3dXIII Oh hi, Is here [releases](https://github.com/zbeboy/Tidy2/releases/tag/1.0) , not release.zip.
